import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { useRouter } from 'next/router'
import { useState, useEffect } from 'react'

export default function Home() {
  const [data, setData] = useState();
  const router = useRouter();
  const apiKey = process.env.NEXT_PUBLIC_API;
  const url = `https://api.nasa.gov/techtransfer/patent/?q=10&engine&api_key=${apiKey}`

  const getTechTransferData = async () => {
    const res = await axios.get(url);
    const info = await res.data;
    console.log(info);
    setData(info);
  }

  useEffect(() => {
    getTechTransferData();
  }, []);

  const handleClick = () => {
    router.push('/polychromatic')
  }
  return (
    <>
      <Head>
        <title>Nasa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>Nasa Gallery</h1>
          <p onClick={handleClick}>Polychromatic Page</p>
          {
            data && data.results.map((tech, index) => {
              return (
                <div className={styles.gallery} key={index}>
                  {
                    tech && tech.map((t, ind) => {
                      if (ind === 10) {
                        return (
                          <Image className={styles.images} src={t} alt={t} key={ind} width={500} height={500} />
                        )
                      }
                    })
                  }
                </div>
              )
            }
            )
          }
        </div>
      </main>
    </>
  )
}
